# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4199428463c6a7759b0fd2a2860f4a8d5087bfca1ce369b18f626f27d3c5d5fa2a51a0f7720f1bdff3792429b06af9f1d0c499d324baafd8a856f149e1a3860b

test:
  secret_key_base: f5f4370023877d842ebc173d1a6c78a39e9261be06c110a594e830686f937cd6f5f6a521f54914eeb3d1b98f30710cdf873495bd29b0ccd1e003ac6c92937a2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
